language: node_js
node_js:
  - '8'
  # Travis-CI Caching
cache:
  directories:
    - node_modules

  before_script:
    - yarn
before_install: - docker pull wming/test
script:
  - yarn build
  - docker build -t wming/test .
  - docker login -u $DOCKER_NAME -p $DOCKER_PWA
  - docker push wming/test
